ALTER TABLE PROPIEDAD
ADD FOREIGN KEY (IdUbicacion) REFERENCES UBICACION(Id); 

ALTER TABLE PROPIEDAD
ADD FOREIGN KEY (TipoPropiedad) REFERENCES INMUEBLE(Id); 

ALTER TABLE PROPIEDAD
ADD FOREIGN KEY (TipoPiso) REFERENCES TIPO_PISO(Id); 

ALTER TABLE PROPIEDAD
ADD FOREIGN KEY (Propietario) REFERENCES VENDEDOR(Correo); 


ALTER TABLE ANUNCIO
ADD FOREIGN KEY (IdPropiedad) REFERENCES PROPIEDAD(Id); 

ALTER TABLE ANUNCIO
ADD FOREIGN KEY (TipoAnuncio) REFERENCES TIPO_ANUNCIO(Nombre); 


ALTER TABLE ANUNCIO
ADD FOREIGN KEY (IdAgente) REFERENCES AGENTE_VENTAS(Correo); 


ALTER TABLE MENSAJE
ADD FOREIGN KEY (IdAnuncio) REFERENCES ANUNCIO(Id); 

ALTER TABLE MENSAJE
ADD FOREIGN KEY (Comprador) REFERENCES COMPRADOR(Correo); 

ALTER TABLE MENSAJE
ADD FOREIGN KEY (Agente) REFERENCES AGENTE_VENTAS(Correo); 

ALTER TABLE COMPRADOR
ADD FOREIGN KEY (IdOcupacion) REFERENCES OCUPACION(Id); 

ALTER TABLE COMPRADOR
ADD FOREIGN KEY (Domicilio) REFERENCES UBICACION(Id); 

ALTER TABLE AGENTE_VENTAS
ADD FOREIGN KEY (PerfilCliente) REFERENCES PERFIL_CLIENTE(Nombre); 

ALTER TABLE AGENTE_VENTAS
ADD FOREIGN KEY (IdNacionalidad) REFERENCES NACIONALIDAD(Id); 

ALTER TABLE AGENTE_VENTAS
ADD FOREIGN KEY (Correo) REFERENCES USUARIO(Correo); 

ALTER TABLE ADMINISTRADOR
ADD FOREIGN KEY (Correo) REFERENCES USUARIO(Correo); 

ALTER TABLE VENDEDOR
ADD FOREIGN KEY (Correo) REFERENCES USUARIO(Correo); 

ALTER TABLE VENDEDOR
ADD FOREIGN KEY (IdNacionalidad) REFERENCES NACIONALIDAD(Id); 

ALTER TABLE FOTOS ADD FOREIGN KEY (IdPropiedad) REFERENCES PROPIEDAD(Id);


