ALTER TABLE PROPIEDAD DROP COLUMN Fotos

CREATE TABLE FOTOS(
	Id INT NOT NULL IDENTITY(1,1),
	Ruta VARCHAR(200),
	IdPropiedad INT NOT NULL,
	PRIMARY KEY (Id)
)

ALTER TABLE FOTOS ADD FOREIGN KEY (IdPropiedad) REFERENCES PROPIEDAD(Id)

DROP TABLE VENDEDOR