CREATE database TECres


CREATE TABLE USUARIO(

	Username VARCHAR(50) NOT NULL,
	Nombre VARCHAR(15) NOT NULL,
	PrimerApellido VARCHAR(15) NOT NULL,
	SegundoApellido VARCHAR(15) NOT NULL,
	FechaIngreso DATE,
	PRIMARY KEY (Username)
)

CREATE TABLE OCUPACION(
	Id INT NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(15) NOT NULL,
	PRIMARY KEY (Id)
)


CREATE TABLE COMPRADOR(

	Username VARCHAR(50) NOT NULL,
	FechaNacimiento DATE NOT NULL,
	IngresoMensual INT NOT NULL,
	IdOcupacion INT NOT NULL,
	Domicilio INT NOT NULL,
	Sexo VARCHAR(5) NOT NULL,
	PRIMARY KEY (Username),
	FOREIGN KEY(Username) REFERENCES USUARIO(Username)
)





CREATE TABLE PERFIL_CLIENTE(
	Nombre VARCHAR(20) NOT NULL,
	Descripcion VARCHAR(50) NOT NULL,
	Predeterminado BIT DEFAULT (0),
	PRIMARY KEY (Nombre)
)

CREATE TABLE CLIENTE(
	Username VARCHAR(50) NOT NULL,
	IdNacionalidad INT NOT NULL,
	Cedula INT NOT NULL,
	PerfilCliente VARCHAR(20) NOT NULL,
	PRIMARY KEY (Username),
	UNIQUE (Cedula)
)


CREATE TABLE ADMINISTRADOR(
	Username VARCHAR(50) NOT NULL,
	Cedula INT NOT NULL,
	PRIMARY KEY (Username),
	UNIQUE (Cedula)
)


CREATE TABLE MENSAJE(
	Id INT NOT NULL IDENTITY(1,1),
	IdAnuncio INT NOT NULL,
	Fecha DATE NOT NULL,
	Hora TIME NOT NULL,
	Texto VARCHAR(80) NOT NULL,
	Comprador VARCHAR(50) NOT NULL,
	Agente VARCHAR(50) NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE ANUNCIO(
	Id INT NOT NULL IDENTITY(1,1),
	IdPropiedad INT NOT NULL,
	TipoAnuncio VARCHAR(30) NOT NULL,
	Tarjeta INT NOT NULL,
	IdAgente VARCHAR(50) NOT NULL,
	Estado BIT DEFAULT(0),
	Venta BIT DEFAULT (1),
	IdPublico INT,
	PRIMARY KEY (Id)
)

CREATE TABLE TIPO_ANUNCIO(
	Nombre VARCHAR(30) NOT NULL,
	Precio INT NOT NULL,
	Predeterminado BIT DEFAULT (0),
	PRIMARY KEY (Nombre)

)

CREATE TABLE PROPIEDAD(
	Id INT NOT NULL IDENTITY(1,1),
	CantidadBanos INT NOT NULL,
	IdUbicacion INT NOT NULL,
	TipoPropiedad INT NOT NULL,
	TamanoLote INT NOT NULL,
	TamanoPropiedad INT NOT NULL,
	Piscina BIT NOT NULL,
	ParqueoVisitas BIT NOT NULL,
	Parqueo BIT NOT NULL,
	TipoPiso INT NOT NULL,
	CantidadNiveles INT DEFAULT (1),
	CantidadHabitaciones INT NOT NULL,
	Precio INT NOT NULL,
	Propietario VARCHAR(50) NOT NULL,
	Gimnasio BIT DEFAULT(0),
	PRIMARY KEY (Id)
)

CREATE TABLE INMUEBLE(
	Id INT NOT NULL IDENTITY(1,1),
	TipoPropiedad VARCHAR(30) NOT NULL, --Cambio
	Predeterminado BIT DEFAULT (0),
	PRIMARY KEY (Id)

)


CREATE TABLE UBICACION(
	Id INT NOT NULL IDENTITY(1,1),
	Provincia VARCHAR(15) NOT NULL,
	Canton VARCHAR(15) NOT NULL,
	Distrito VARCHAR(50) NOT NULL,
	PRIMARY KEY (Id)

)

CREATE TABLE TIPO_PISO(
	Id INT NOT NULL IDENTITY(1,1),
	Piso VARCHAR(30) NOT NULL,
	Predeterminado BIT DEFAULT (0),
	PRIMARY KEY (Id)

)

CREATE TABLE NACIONALIDAD(
	Id INT NOT NULL IDENTITY(1,1),
	Nacionalidad VARCHAR(30) NOT NULL,
	PRIMARY KEY (Id)
)


CREATE TABLE FOTOS(
	Id INT NOT NULL IDENTITY(1,1),
	Ruta VARCHAR(300),
	IdPropiedad INT NOT NULL,
	PRIMARY KEY (Id)
)


CREATE TABLE PUBLICO(
	Id INT NOT NULL IDENTITY(1,1),
	FechaInicial DATE NOT NULL,
	FechaFinal DATE NOT NULL,
	CantidadMensajes INT NOT NULL,
	IngresoInicial INT NOT NULL,
	IngresoFinal INT NOT NULL,
	Sexo VARCHAR(5) NOT NULL,
	EdadInicial INT NOT NULL,
	EdadFinal INT NOT NULL,
	PRIMARY KEY (Id)
)
