---DATOS

INSERT INTO NACIONALIDAD(Nacionalidad)
VALUES
('Afgano'),
('Alemán'),
('Árabe'),
('Argentino'),
('Australiano'),
('Belga'),
('Boliviano'),
('Brasileño'),
('Camboyano'),
('Canadiense'),
('Chileno'),
('Chino'),
('Colombiano'),
('Coreano'),
('Costarricense'),
('Cubano'),
('Danés'),
('Ecuatoriano'),
('Egipcio'),
('Salvadoreño'),
('Escocés'),
('Español'),
('Estadounidense'),
('Estonio'),
('Etiope'),
('Filipino'),
('Finlandés'),
('Francés'),
('Galés'),
('Griego'),
('Guatemalteco'),
('Haitiano'),
('Holandés'),
('Hondureño'),
('Indonés'),
('inglés'),
('Iraquí'),
('Iraní'),
('Irlandés'),
('Israelí'),
('Italiano'),
('Japonés'),
('Jordano'),
('Laosiano'),
('Letón'),
('Letonés'),
('Malayo'),
('Marroquí'),
('Mexicano'),
('Nicaragüense'),
('Noruego'),
('Neozelandés'),
('Panameño'),
('Paraguayo'),
('Peruano'),
('Polaco'),
('Portugués'),
('Puertorriqueño'),
('Dominicano'),
('Rumano'),
('Ruso'),
('Sueco'),
('Suizo'),
('Tailandés'),
('Taiwanes'),
('Turco'),
('Ucraniano'),
('Uruguayo'),
('Venezolano'),
('Vietnamita')



INSERT INTO UBICACION (Provincia,Canton,Distrito)
VALUES
 ('San Jose','San Jose','Carmen'),
 ('San Jose','San Jose','Merced'),
 ('San Jose','San Jose','Hospital'),
 ('San Jose','San Jose','Catedral'),
 ('San Jose','San Jose','Zapote'),
 ('San Jose','San Jose','San Francisco de dos Rios'),
 ('San Jose','San Jose','La Uruca'),
 ('San Jose','San Jose','Mata Redonda'),
 ('San Jose','San Jose','Pavas'),
 ('San Jose','San Jose','Hatillo'),
 ('San Jose','San Jose','San Sebastian'),
 ('San Jose','Escazu','Escazu'),
 ('San Jose','Escazu','San Antonio'),
 ('San Jose','Escazu','San Rafael'),
 ('San Jose','Desamparados','Desamparados'),
 ('San Jose','Desamparados','San Miguel'),
 ('San Jose','Desamparados','San Juan de Dios'),
 ('San Jose','Desamparados','San Rafael Arriba'),
 ('San Jose','Desamparados','San Antonio'),
 ('San Jose','Desamparados','Frailes'),
 ('San Jose','Desamparados','Patarra'),
 ('San Jose','Desamparados','San Cristobal'),
 ('San Jose','Desamparados','Rosario'),
 ('San Jose','Desamparados','Damas'),
 ('San Jose','Desamparados','San Rafael Abajo'),
 ('San Jose','Desamparados','Gravillas'),
 ('San Jose','Desamparados','Los Guido'),
 ('San Jose','Puriscal','Santiago'),
 ('San Jose','Puriscal','Mercedes Sur'),
 ('San Jose','Puriscal','Barbacoas'),
 ('San Jose','Puriscal','Grifo Alto'),
 ('San Jose','Puriscal','San Rafael'),
 ('San Jose','Puriscal','Candelarita'),
 ('San Jose','Puriscal','Desamparaditos'),
 ('San Jose','Puriscal','San Antonio'),
 ('San Jose','Puriscal','Chires'),
 ('San Jose','Tarrazu','San Marcos'),
 ('San Jose','Tarrazu','San Lorenzo'),
 ('San Jose','Tarrazu','San Carlos'),
 ('San Jose','Aserri','Aserri'),
 ('San Jose','Aserri','Tarbaca'),
 ('San Jose','Aserri','Vuelta de Jorco'),
 ('San Jose','Aserri','San Gabriel'),
 ('San Jose','Aserri','Legua'),
 ('San Jose','Aserri','Monterrey'),
 ('San Jose','Aserri','Salitrillos'),
 ('San Jose','Mora','Colon'),
 ('San Jose','Mora','Guayabo'),
 ('San Jose','Mora','tabarcia'),
 ('San Jose','Mora','Piedras Negras'),
 ('San Jose','Mora','Picagres'),
 ('San Jose','Mora','Jaris'),
 ('San Jose','Mora','Quitirrise'),
 ('San Jose','Goicoechea','Guadalupe'),
 ('San Jose','Goicochea','San Francisco'),
 ('San Jose','Goicoechea','Calle Blancos'),
 ('San Jose','Goicochea','Mata de Platano'),
 ('San Jose','Goicoechea','Ipis'),
 ('San Jose','Goicoechea','Rancho Redondo'),
 ('San Jose','Goicoechea','Purral'),
 ('San Jose','Santa Ana','Santa Ana'),
 ('San Jose','Santa Ana','Salitral'),
 ('San Jose','Santa Ana','Pozos'),
 ('San Jose','Santa Ana','uruca'),
 ('San Jose','Santa Ana','Piedades'),
 ('San Jose','Santa Ana','Brasil'),
 ('San Jose','Alajuelita','Alajuelita'),
 ('San Jose','Alajuelita','San Josecito'),
 ('San Jose','Alajuelita','San Antonio'),
 ('San Jose','Alajuelita','Concepcion'),
 ('San Jose','Alajuelita','San Felipe'),
 ('San Jose','Vazquez de Coronado','San Isidro'),
 ('San Jose','Vazquez de Coronado','San Rafael'),
 ('San Jose','Vazquez de Coronado','Dulce Nombre'),
 ('San Jose','Vazquez de Coronado','Patalillo'),
 ('San Jose','Vazquez de Coronado','Cascajal'),
 ('San Jose','Acosta','San Ignacio'),
 ('San Jose','Acosta','Guatil'),
 ('San Jose','Acosta','Palmichal'),
 ('San Jose','Acosta','Cangrejal'),
 ('San Jose','Acosta','Sabanillas'),
 ('San Jose','Tibas','San Juan'),
 ('San Jose','Tibas','Cinco Esquinas'),
 ('San Jose','Tibas','Anselmo Llorente'),
 ('San Jose','Tibas','Leon XIII'),
 ('San Jose','Tibas','Colima'),
 ('San Jose','Moravia','San Vicente'),
 ('San Jose','Moravia','San Jeronimo'),
 ('San Jose','Moravia','La Trinidad'),
 ('San Jose','Montes de Oca','San Pedro'),
 ('San Jose','Montes de Oca','Sabanilla'),
 ('San Jose','Montes de Oca','Mercedes'),
 ('San Jose','Montes de Oca','San Rafael'),
 ('San Jose','Turrubares','San Pablo'),
 ('San Jose','Turrubares','San Pedro'),
 ('San Jose','Turrubares','San Juan de Mata'),
 ('San Jose','Turrubares','San Luis'),
 ('San Jose','Turrubares','Carara'),
 ('San Jose','Dota','Santa Maria'),
 ('San Jose','Dota','Jardin'),
 ('San Jose','Dota','Copey'),
 ('San Jose','Curridabat','Curridabat'),
 ('San Jose','Curridabat','Granadilla'),
 ('San Jose','Curridabat','Sanchez'),
 ('San Jose','Curridabat','Tirrases'),
 ('San Jose','Perez Zeledon','San Isidro de el General'),
 ('San Jose','Perez Zeledon','El General'),
 ('San Jose','Perez Zeledon','Daniel Flores'),
 ('San Jose','Perez Zeledon','Rivas'),
 ('San Jose','Perez Zeledon','San Pedro'),
 ('San Jose','Perez Zeledon','Platanares'),
 ('San Jose','Perez Zeledon','Pejibaye'),
 ('San Jose','Perez Zeledon','Cajon'),
 ('San Jose','Perez Zeledon','Baru'),
 ('San Jose','Perez Zeledon','Rio Nuevo'),
 ('San Jose','Perez Zeledon','Paramo'),
 ('San Jose','Perez Zeledon','La Amistad'),
 ('San Jose','Leon Cortes Castro','San Pablo'),
 ('San Jose','Leon Cortes Castro','San Andres'),
 ('San Jose','Leon Cortes Castro','Llano Bonito'),
 ('San Jose','Leon Cortes Castro','San Isidro'),
 ('San Jose','Leon Cortes Castro','Santa Cruz'),
 ('San Jose','Leon Cortes Castro','San Antonio'),
 ('Alajuela','Alajuela','Alajuela'),
 ('Alajuela','Alajuela','San Jose'),
 ('Alajuela','Alajuela','Carrizal'),
 ('Alajuela','Alajuela','San Antonio'),
 ('Alajuela','Alajuela','Guacima'),
 ('Alajuela','Alajuela','Sa Isidro'),
 ('Alajuela','Alajuela','Sabanilla'),
 ('Alajuela','Alajuela','San Rafael'),
 ('Alajuela','Alajuela','Rio Segundo'),
 ('Alajuela','Alajuela','Desamparados'),
 ('Alajuela','Alajuela','Turrucares'),
 ('Alajuela','Alajuela','Tambor'),
 ('Alajuela','Alajuela','Garita'),
 ('Alajuela','Alajuela','Sarapiqui'),
 ('Alajuela','San Ramon','San Ramon'),
 ('Alajuela','San Ramon','Santiago'),
 ('Alajuela','San Ramon','San Juan'),
 ('Alajuela','San Ramon','Piedades Norte'),
 ('Alajuela','San Ramon','Piedades Sur'),
 ('Alajuela','San Ramon','San Rafael'),
 ('Alajuela','San Ramon','San Isidro'),
 ('Alajuela','San Ramon','Angeles'),
 ('Alajuela','San Ramon','Alfaro'),
 ('Alajuela','San Ramon','Volio'),
 ('Alajuela','San Ramon','Concepcion'),
 ('Alajuela','San Ramon','Zapotal'),
 ('Alajuela','San Ramon','Peñas Blancas'),
 ('Alajuela','San Ramon','San Lorenzo'),
 ('Alajuela','Grecia','Grecia'),
 ('Alajuela','Grecia','San isidro'),
 ('Alajuela','Grecia','San Jose'),
 ('Alajuela','Grecia','San Roque'),
 ('Alajuela','Grecia','Tacares'),
 ('Alajuela','Grecia','Rio Cuarto'),
 ('Alajuela','Grecia','Peunte de Piedra'),
 ('Alajuela','Grecia','Bolivar'),
 ('Alajuela','San Mateo','San Mateo'),
 ('Alajuela','San Mateo','Desmonte'),
 ('Alajuela','San Mateo','Jesus Maria'),
 ('Alajuela','San Mateo','Labrador'),
 ('Alajuela','Atenas','Atenas'),
 ('Alajuela','Atenas','Jesus'),
 ('Alajuela','Atenas','Mercedes'),
 ('Alajuela','Atenas','San Isidro'),
 ('Alajuela','Atenas','Concepcion'),
 ('Alajuela','Atenas','San Jose'),
 ('Alajuela','Atenas','Santa Eulalia'),
 ('Alajuela','Atenas','Escobal'),
 ('Alajuela','Naranjo','Naranjo'),
 ('Alajuela','Naranjo','San Miguel'),
 ('Alajuela','Naranjo','San Jose'),
 ('Alajuela','Naranjo','Cirri Sur'),
 ('Alajuela','Naranjo','San Jeronimo'),
 ('Alajuela','Naranjo','San Juan'),
 ('Alajuela','Naranjo','El Rosario'),
 ('Alajuela','Naranjo','Palmitos'),
 ('Alajuela','Palmares','Palmares'),
 ('Alajuela','Palmares','Zaragoza'),
 ('Alajuela','Palmares','Buenos Aires'),
 ('Alajuela','Palmares','Santiago'),
 ('Alajuela','Palmares','Candelaria'),
 ('Alajuela','Palmares','Esquipulas'),
 ('Alajuela','Palmares','La Granja'),
 ('Alajuela','Poas','San Pedro'),
 ('Alajuela','Poas','San Juan'),
 ('Alajuela','Poas','San Rafael'),
 ('Alajuela','Poas','Carrillos'),
 ('Alajuela','Poas','Sabana Redonda'),
 ('Alajuela','Orotina','Orotina'),
 ('Alajuela','Orotina','El Mastate'),
 ('Alajuela','Orotina','Hacienda Vieja'),
 ('Alajuela','Orotina','Coyolar'),
 ('Alajuela','Orotina','La Ceiba'),
 ('Alajuela','San Carlos','Quesada'),
 ('Alajuela','San Carlos','Florencia'),
 ('Alajuela','San Carlos','Buenavista'),
 ('Alajuela','San Carlos','Aguas Zarcas'),
 ('Alajuela','San Carlos','Venecia'),
 ('Alajuela','San Carlos','Pital'),
 ('Alajuela','San Carlos','La Fortuna'),
 ('Alajuela','San Carlos','La Tigra'),
 ('Alajuela','San Carlos','La Palmera'),
 ('Alajuela','San Carlos','Venado'),
 ('Alajuela','San Carlos','Cutris'),
 ('Alajuela','San Carlos','Monterrey'),
 ('Alajuela','San Carlos','Pocosol'),
 ('Alajuela','Zarcero','Zarcero'),
 ('Alajuela','Zarcero','Laguna'),
 ('Alajuela','Zarcero','Tapesco'),
 ('Alajuela','Zarcero','Guadalupe'),
 ('Alajuela','Zarcero','Palmira'),
 ('Alajuela','Zarcero','Zapote'),
 ('Alajuela','Zarcero','Brisas'),
 ('Alajuela','Valverde Vega','Sarchi Norte'),
 ('Alajuela','Valverde Vega','Sarchi Sur'),
 ('Alajuela','Valverde Vega','Toro Amarillo'),
 ('Alajuela','Valverde Vega','San Pedro'),
 ('Alajuela','Valverde Vega','Rodriguez'),
 ('Alajuela','Upala','Upala'),
 ('Alajuela','Upala','Aguas Claras'),
 ('Alajuela','Upala','San Jose'),
 ('Alajuela','Upala','Bijagua'),
 ('Alajuela','Upala','Delicias'),
 ('Alajuela','Upala','Dos Rios'),
 ('Alajuela','Upala','Yolillal'),
 ('Alajuela','Upala','Canalete'),
 ('Alajuela','Los Chiles','Los Chiles'),
 ('Alajuela','Los Chiles','Caño Negro'),
 ('Alajuela','Los Chiles','El Amparo'),
 ('Alajuela','Los Chiles','San Jorge'),
 ('Alajuela','Guatuso','San Rafael'),
 ('Alajuela','Guatuso','Buenavista'),
 ('Alajuela','Guatuso','Cote'),
 ('Alajuela','Guatuso','Katira'),
 ('Alajuela','Rio Cuarto','Rio Cuarto'),
 ('Alajuela','Rio Cuarto','Santa Isabel'),
 ('Alajuela','Rio Cuarto','Santa Rita'),
 ('Cartago','Cartago','Oriental'),
 ('Cartago','Cartago','Occidental'),
 ('Cartago','Cartago','Carmen'),
 ('Cartago','Cartago','San Nicolas'),
 ('Cartago','Cartago','Aguacaliente'),
 ('Cartago','Cartago','Guadalupe'),
 ('Cartago','Cartago','Corralillo'),
 ('Cartago','Cartago','Tierra Blanca'),
 ('Cartago','Cartago','Dulce Nombre'),
 ('Cartago','Cartago','Llano Grande'),
 ('Cartago','Cartago','Quebradilla'),
 ('Cartago','Paraiso','Paraiso'),
 ('Cartago','Paraiso','Santiago'),
 ('Cartago','Paraiso','Orosi'),
 ('Cartago','Paraiso','Cachi'),
 ('Cartago','Paraiso','Llanos de Santa Lucia'),
 ('Cartago','La Union','Tres Rios'),
 ('Cartago','La Union','San Diego'),
 ('Cartago','La Union','San Juan'),
 ('Cartago','La Union','San Rafael'),
 ('Cartago','La Union','Concepcion'),
 ('Cartago','La Union','Dulce Nombre'),
 ('Cartago','La Union','San Ramon'),
 ('Cartago','La Union','Rio Azul'),
 ('Cartago','Jimenez','Juan Viñas'),
 ('Cartago','Jimenez','Tucurrique'),
 ('Cartago','Jimenez','Pejibaye'),
 ('Cartago','Turrialba','Turrialba'),
 ('Cartago','Turrialba','La Suiza'),
 ('Cartago','Turrialba','Peralta'),
 ('Cartago','Turrialba','Santa Cruz'),
 ('Cartago','Turrialba','Santa Teresita'),
 ('Cartago','Turrialba','Pavones'),
 ('Cartago','Turrialba','Tuis'),
 ('Cartago','Turrialba','Tayutic'),
 ('Cartago','Turrialba','Santa Rosa'),
 ('Cartago','Turrialba','Tres Equis'),
 ('Cartago','Turrialba','La Isabel'),
 ('Cartago','Turrialba','Chirripo'),
 ('Cartago','Alvarado','Pacayas'),
 ('Cartago','Alvarado','Cervantes'),
 ('Cartago','Alvarado','Capellades'),
 ('Cartago','Oreamuno','San Rafael'),
 ('Cartago','Oreamuno','Cot'),
 ('Cartago','Oreamuno','Potrero Cerrado'),
 ('Cartago','Oreamuno','Cipreses'),
 ('Cartago','Oreamuno','Santa Rosa'),
 ('Cartago','El Guarco','El Tejar'),
 ('Cartago','El Guarco','San Isidro'),
 ('Cartago','El Guarco','Tobosi'),
 ('Cartago','El Guarco','Patio de Agua'),
 ('Heredia','Heredia','Heredia'),
 ('Heredia','Heredia','Mercedes'),
 ('Heredia','Heredia','San Francisco'),
 ('Heredia','Heredia','Ulloa'),
 ('Heredia','Heredia','Varablanca'),
 ('Heredia','Barva','Barva'),
 ('Heredia','Barva','San Pedro'),
 ('Heredia','Barva','San Pablo'),
 ('Heredia','Barva','San Roque'),
 ('Heredia','Barva','Santa Lucia'),
 ('Heredia','Barva','San Jose de la Montaña'),
 ('Heredia','Santo Domingo','Santo Domingo'),
 ('Heredia','Santo Domingo','San Vicente'),
 ('Heredia','Santo Domingo','San Miguel'),
 ('Heredia','Santo Domingo','Paracito'),
 ('Heredia','Santo Domingo','Santo Tomas'),
 ('Heredia','Santo Domingo','Santa Rosa'),
 ('Heredia','Santo Domingo','Tures'),
 ('Heredia','Santo Domingo','Para'),
 ('Heredia','Santa Barbara','Santa Barbara'),
 ('Heredia','Santa Barbara','San Pedro'),
 ('Heredia','Santa Barbara','San Juan'),
 ('Heredia','Santa Barbara','Jesus'),
 ('Heredia','Santa Barbara','Santo Domingo'),
 ('Heredia','Santa Barbara','Puraba'),
 ('Heredia','San Rafael','San Rafael'),
 ('Heredia','San Rafael','San Josecito'),
 ('Heredia','San Rafael','Santiago'),
 ('Heredia','San Rafael','Angeles'),
 ('Heredia','San Rafael','Concepcion'),
 ('Heredia','San Isidro','San Isidro'),
 ('Heredia','San Isidro','San Jose'),
 ('Heredia','San Isidro','Concepcion'),
 ('Heredia','San Isidro','San Francisco'),
 ('Heredia','Belen','San Antonio'),
 ('Heredia','Belen','La Ribera'),
 ('Heredia','Belen','La Asuncion'),
 ('Heredia','Flores','San Joaquin'),
 ('Heredia','Flores','Barrantes'),
 ('Heredia','Flores','Llorente'),
 ('Heredia','San Pablo','San Pablo'),
 ('Heredia','San Pablo','Rincon de Sabanilla'),
 ('Heredia','Sarapiqui','Puerto Viejo'),
 ('Heredia','Sarapiqui','La Virgen'),
 ('Heredia','Sarapiqui','Las Horquetas'),
 ('Heredia','Sarapiqui','Llanuras del Gaspar'),
 ('Heredia','Sarapiqui','Cureña'),
 ('Guanacaste','Liberia','Liberia'),
 ('Guanacaste','Liberia','Cañas Dulces'),
 ('Guanacaste','Liberia','Mayorga'),
 ('Guanacaste','Liberia','Nacascolo'),
 ('Guanacaste','Liberia','Curubande'),
 ('Guanacaste','Nicoya','Nicoya'),
 ('Guanacaste','Nicoya','Mansion'),
 ('Guanacaste','Nicoya','San Antonio'),
 ('Guanacaste','Nicoya','Quebrada Honda'),
 ('Guanacaste','Nicoya','Samara'),
 ('Guanacaste','Nicoya','Nosara'),
 ('Guanacaste','Nicoya','Belen de Nosarita'),
 ('Guanacaste','Santa Cruz','Santa Cruz'),
 ('Guanacaste','Santa Cruz','Bolson'),
 ('Guanacaste','Santa Cruz','Ventisiete de Abril'),
 ('Guanacaste','Santa Cruz','Tempate'),
 ('Guanacaste','Santa Cruz','Cartagena'),
 ('Guanacaste','Santa Cruz','Cuajiniquil'),
 ('Guanacaste','Santa Cruz','Diria'),
 ('Guanacaste','Santa Cruz','Cabo Velas'),
 ('Guanacaste','Santa Cruz','Tamarindo'),
 ('Guanacaste','Bagaces','Bagaces'),
 ('Guanacaste','Bagaces','La Fortuna'),
 ('Guanacaste','Bagaces','Mogote'),
 ('Guanacaste','Bagaces','Rio Naranjo'),
 ('Guanacaste','Carrillo','Filadelfia'),
 ('Guanacaste','Carrillo','Palmira'),
 ('Guanacaste','Carrillo','Sardinal'),
 ('Guanacaste','Carrillo','Belen'),
 ('Guanacaste','Cañas','Cañas'),
 ('Guanacaste','Cañas','Palmira'),
 ('Guanacaste','Cañas','San Miguel'),
 ('Guanacaste','Cañas','Bebedero'),
 ('Guanacaste','Cañas','Porozal'),
 ('Guanacaste','Abangares','Las Juntas'),
 ('Guanacaste','Abangares','Sierra'),
 ('Guanacaste','Abangares','San Juan'),
 ('Guanacaste','Abangares','Colorado'),
 ('Guanacaste','Tilaran','Tilaran'),
 ('Guanacaste','Tilaran','Quebrada Grande'),
 ('Guanacaste','Tilaran','Tronadora'),
 ('Guanacaste','Tilaran','Santa Rosa'),
 ('Guanacaste','Tilaran','Libano'),
 ('Guanacaste','Tilaran','Tierras Morenas'),
 ('Guanacaste','Tilaran','Arenal'),
 ('Guanacaste','Nandayure','Carmona'),
 ('Guanacaste','Nandayure','Santa Rita'),
 ('Guanacaste','Nandayure','Zapotal'),
 ('Guanacaste','Nandayure','San Pablo'),
 ('Guanacaste','Nandayure','Porvenir'),
 ('Guanacaste','Nandayure','Bejuco'),
 ('Guanacaste','La Cruz','La Cruz'),
 ('Guanacaste','La Cruz','Santa Cecilia'),
 ('Guanacaste','La Cruz','La Garita'),
 ('Guanacaste','La Cruz','Santa Elena'),
 ('Guanacaste','Hojancha','Hojancha'),
 ('Guanacaste','Hojancha','Monte Romo'),
 ('Guanacaste','Hojancha','Puerto Carrillo'),
 ('Guanacaste','Hojancha','Huacas'),
 ('Puntarenas','Puntarenas','Puntarenas'),
 ('Puntarenas','Puntarenas','Pitahaya'),
 ('Puntarenas','Puntarenas','Chomes'),
 ('Puntarenas','Puntarenas','lepanto'),
 ('Puntarenas','Puntarenas','Paquera'),
 ('Puntarenas','Puntarenas','Manzanillo'),
 ('Puntarenas','Puntarenas','Guacimal'),
 ('Puntarenas','Puntarenas','Barranca'),
 ('Puntarenas','Puntarenas','Monte Verde'),
 ('Puntarenas','Puntarenas','Isla del Coco'),
 ('Puntarenas','Puntarenas','Cobano'),
 ('Puntarenas','Puntarenas','Chacarita'),
 ('Puntarenas','Puntarenas','Chira'),
 ('Puntarenas','Puntarenas','Acapulco'),
 ('Puntarenas','Puntarenas','El Roble'),
 ('Puntarenas','Puntarenas','Aranciba'),
 ('Puntarenas','Esparza','Espiritu Santo'),
 ('Puntarenas','Esparza','San Juan Grande'),
 ('Puntarenas','Esparza','Macacona'),
 ('Puntarenas','Esparza','San Rafael'),
 ('Puntarenas','Esparza','San Jeronimo'),
 ('Puntarenas','Esparza','Caldera'),
 ('Puntarenas','Buenos Aires','Buenos Aires'),
 ('Puntarenas','Buenos Aires','Volcan'),
 ('Puntarenas','Buenos Aires','Potrero Grande'),
 ('Puntarenas','Buenos Aires','Boruca'),
 ('Puntarenas','Buenos Aires','Pilas'),
 ('Puntarenas','Buenos Aires','Colinas'),
 ('Puntarenas','Buenos Aires','Changuena'),
 ('Puntarenas','Buenos Aires','Biolley'),
 ('Puntarenas','Buenos Aires','Brunka'),
 ('Puntarenas','Montes de Oro','Miramar'),
 ('Puntarenas','Montes de Oro','La Union'),
 ('Puntarenas','Montes de Oro','San Isidro'),
 ('Puntarenas','Osa','Puerto Cortes'),
 ('Puntarenas','Osa','Palmar'),
 ('Puntarenas','Osa','Sierpe'),
 ('Puntarenas','Osa','Bahia Ballena'),
 ('Puntarenas','Osa','Piedras Blancas'),
 ('Puntarenas','Osa','Bahia Drake'),
 ('Puntarenas','Quepos','Quepos'),
 ('Puntarenas','Quepos','Savegre'),
 ('Puntarenas','Quepos','Naranjito'),
 ('Puntarenas','Golfito','Golfito'),
 ('Puntarenas','Golfito','Puerto Jimenez'),
 ('Puntarenas','Golfito','Guaycara'),
 ('Puntarenas','Golfito','Pavon'),
 ('Puntarenas','Coto Brus','San Vito'),
 ('Puntarenas','Coto Brus','Sabalito'),
 ('Puntarenas','Coto Brus','Aguabuena'),
 ('Puntarenas','Coto Brus','Limoncito'),
 ('Puntarenas','Coto Brus','Pittier'),
 ('Puntarenas','Coto Brus','Gutierrez Braun'),
 ('Puntarenas','Parrita','Parrita'),
 ('Puntarenas','Corredores','Corredor'),
 ('Puntarenas','Corredores','La Cuesta'),
 ('Puntarenas','Corredores','Canoas'),
 ('Puntarenas','Corredores','Laurel'),
 ('Puntarenas','Garabito','Jaco'),
 ('Puntarenas','Garabito','Tarcoles'),
 ('Limon','Limon','Limon'),
 ('Limon','Limon','Valle La Estrella'),
 ('Limon','Limon','Rio Blanco'),
 ('Limon','Limon','Matama'),
 ('Limon','Pocosi','Guapiles'),
 ('Limon','Pocosi','Jimenez'),
 ('Limon','Pocosi','Rita'),
 ('Limon','Pocosi','Roxana'),
 ('Limon','Pocosi','Cariari'),
 ('Limon','Pocosi','Colorado'),
 ('Limon','Pocosi','La Colonia'),
 ('Limon','Siquirres','Siquirres'),
 ('Limon','Siquirres','Pacuarito'),
 ('Limon','Siquirres','Florida'),
 ('Limon','Siquirres','Germania'),
 ('Limon','Siquirres','El Cairo'),
 ('Limon','Siquirres','Alegria'),
 ('Limon','Talamanca','Bratsi'),
 ('Limon','Talamanca','Sixaola'),
 ('Limon','Talamanca','Cahuita'),
 ('Limon','Talamanca','Telire'),
 ('Limon','Matina','Matina'),
 ('Limon','Matina','Batan'),
 ('Limon','Matina','Carrandi'),
 ('Limon','Guacimo','Guacimo'),
 ('Limon','Guacimo','Mercedes'),
 ('Limon','Guacimo','Pocora'),
 ('Limon','Guacimo','Rio Jimenez'),
 ('Limon','Guacimo','Duacari');


INSERT INTO TIPO_PISO (Piso,Predeterminado)
VALUES ('Concreto Lujado',1),('Porcelanato',1),('Ceramica',1);

INSERT INTO OCUPACION(Nombre)
VALUES('Ingeniero'),
('Medico'),('Estilista'),('Enfermero'),('Veterinario');

INSERT INTO INMUEBLE(TipoPropiedad, Predeterminado)
VALUES('Lote',1),('Casa',1),('Apartamento',1),('Finca',0),('Ganaderia',0),('Oficina',0)

INSERT INTO PERFIL_CLIENTE(Nombre,Descripcion,Predeterminado)
VALUES('Agente','a',1),('Constructor','s',1),('Propietario','u',1),('Anunciante','d',1);

EXEC NuevoCliente 'jp','dsar25','as@gmail.com','Jose','Pablo','Mendez','2017-03-28',1,11659056,'Agente'



insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Parisian Group', 3, 110, 3, 846, 1107, 1, 1, 1, 2, 1, 2, 614819846, 1,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Brekke-Bernier', 5, 114, 3, 455, 252, 0, 1, 0, 1, 2, 5, 720855613, 0,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Thompson-Ankunding', 2, 114, 3, 368, 1895, 0, 0, 1, 1, 1, 0, 258035534, 0,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Bartell-Jaskolski', 3, 110, 3, 752, 1302, 1, 0, 0, 3, 1, 2, 920615224, 1,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Schultz-Goldner', 3, 114, 1, 540, 827, 1, 1, 1, 3, 2, 3, 135510435, 0,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Mueller-Wunsch', 4, 112, 1, 453, 1185, 0, 1, 0, 3, 2, 5, 40421256, 1,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Okuneva and Sons', 1, 113, 3, 123, 1583, 0, 0, 1, 3, 1, 0, 415428799, 0,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Bode-Dickinson', 1, 113, 1, 196, 1116, 0, 1, 1, 3, 2, 4, 216116730, 1,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Nader-Fisher', 2, 115, 2, 997, 925, 0, 1, 1, 3, 2, 1, 929340456, 1,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Mueller, Rodriguez and Dicki', 5, 15, 2, 108, 1421, 1, 1, 1, 1, 1, 4, 221190729, 0,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Tremblay-Lemke', 2, 110, 3, 890, 596, 0, 0, 0, 3, 2, 1, 291599462, 1,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Cruickshank Group', 114, 110, 2, 533, 978, 0, 1, 0, 2, 1, 0, 354759506, 0,'jp');
insert into PROPIEDAD (Titulo, CantidadBanos, IdUbicacion, TipoPropiedad, TamanoLote, TamanoPropiedad, Piscina, ParqueoVisitas, Parqueo, TipoPiso, CantidadNiveles, CantidadHabitaciones, Precio, Gimnasio,Propietario) values ('Kuhn and Sons', 4, 116, 12, 910, 666, 0, 1, 1, 3, 2, 2, 702226452, 1,'jp');
