// <auto-generated />
namespace TECres_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changedDefaultTableNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedDefaultTableNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201909142142082_changedDefaultTableNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
