//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public string Username { get; set; }
        public int Cedula { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
