//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANUNCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANUNCIO()
        {
            this.MENSAJE = new HashSet<MENSAJE>();
        }
    
        public int Id { get; set; }
        public int IdPropiedad { get; set; }
        public string TipoAnuncio { get; set; }
        public int Tarjeta { get; set; }
        public string IdAgente { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> Venta { get; set; }
        public Nullable<int> IdPublico { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PROPIEDAD PROPIEDAD { get; set; }
        public virtual PUBLICO PUBLICO { get; set; }
        public virtual TIPO_ANUNCIO TIPO_ANUNCIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAJE> MENSAJE { get; set; }
    }
}
