//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRADOR()
        {
            this.MENSAJE = new HashSet<MENSAJE>();
        }
    
        public string Username { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int IngresoMensual { get; set; }
        public int IdOcupacion { get; set; }
        public int Domicilio { get; set; }
        public string Sexo { get; set; }
    
        public virtual UBICACION UBICACION { get; set; }
        public virtual OCUPACION OCUPACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAJE> MENSAJE { get; set; }
    }
}
