//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAJE
    {
        public int Id { get; set; }
        public int IdAnuncio { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Texto { get; set; }
        public string Comprador { get; set; }
        public string Agente { get; set; }
    
        public virtual ANUNCIO ANUNCIO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual COMPRADOR COMPRADOR1 { get; set; }
    }
}
