//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIEDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPIEDAD()
        {
            this.ANUNCIO = new HashSet<ANUNCIO>();
            this.FOTOS = new HashSet<FOTOS>();
        }
    
        public int Id { get; set; }
        public int CantidadBanos { get; set; }
        public int IdUbicacion { get; set; }
        public int TipoPropiedad { get; set; }
        public int TamanoLote { get; set; }
        public int TamanoPropiedad { get; set; }
        public bool Piscina { get; set; }
        public bool ParqueoVisitas { get; set; }
        public bool Parqueo { get; set; }
        public int TipoPiso { get; set; }
        public Nullable<int> CantidadNiveles { get; set; }
        public int CantidadHabitaciones { get; set; }
        public int Precio { get; set; }
        public string Propietario { get; set; }
        public Nullable<bool> Gimnasio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANUNCIO> ANUNCIO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTOS> FOTOS { get; set; }
        public virtual INMUEBLE INMUEBLE { get; set; }
        public virtual UBICACION UBICACION { get; set; }
        public virtual TIPO_PISO TIPO_PISO { get; set; }
    }
}
