//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tec_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string Username { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual COMPRADOR COMPRADOR { get; set; }
    }
}
